services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ultra
      POSTGRES_PASSWORD: ultra
      POSTGRES_DB: ultra_todo
    ports: [ "5432:5432" ]
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ultra -d ultra_todo" ]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7-alpine
    command: [ "redis-server", "--save", "60", "1", "--loglevel", "warning" ]
    ports: [ "6379:6379" ]
    volumes:
      - redisdata:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  pgdata: {}
  redisdata: {}
